### PR TITLE
Update node and deps

### PR DESCRIPTION
**Pull request by NiharR27**
Updating node12 to node20 to get rid of the warning on ci:

The following actions uses node12 which is deprecated and will be forced to run on node16: thomaseizinger/create-release@1.0.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

OR

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: thomaseizinger/create-release@1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### CODE REVIEW

**Comment by NiharR027** [comment]
cc @thomaseizinger - created a brand new PR. lemme know if all good. Thnx 🙏

**Review by thomaseizinger — APPROVED** [review]
Awesome, thank you very much! :pray:

**Comment by thomaseizinger** [comment]
I'd appreciate if you could test-drive latest `master` wherever you use this. If everything is good, I am happy to make a release after!

**Comment by NiharR027** [comment]
@thomaseizinger - can confirm that it went fine without any warnings/errors:

Screenshot 2024-08-27 at 1 15 03 PM
Screenshot 2024-08-27 at 1 15 28 PM
Screenshot 2024-08-27 at 1 15 43 PM

**Comment by NiharR27** [comment]
@thomaseizinger - thanks 🙏 for merging. Any chance we can do a mini release with a new version for this? If not then I will just use master for now. Cheers.

**Comment by thomaseizinger** [comment]
Yeah was about to make one.

**Comment by thomaseizinger** [comment]
Done!

**Comment by NiharR27** [comment]
danke :)

**Pull request merged**
