### PR TITLE
Update to node20

### PR DESCRIPTION
**Pull request by NiharR027**
As per the comment on this PR: https://github.com/thomaseizinger/create-release/pull/3#pullrequestreview-2153463809

Updating node12 to node20 to get rid of the warning on ci:

```
The following actions uses node12 which is deprecated and will be forced to run on node16: thomaseizinger/create-release@1.0.0. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

**OR**

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: thomaseizinger/create-release@1.0.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Can you re-generate the `index.js` with Node 20? We need to make sure it actually works with Node 20.

**Comment by NiharR027** [comment]
> Can you re-generate the `index.js` with Node 20? We need to make sure it actually works with Node 20.

True, can do after work 👌 Thanks for the reply.

**Comment by NiharR027** [comment]
> > Can you re-generate the `index.js` with Node 20? We need to make sure it actually works with Node 20.
> 
> True, can do after work 👌 Thanks for the reply.

Hi @thomaseizinger - silly question, but how do I re-generate the index.js file?

**Comment by thomaseizinger** [comment]
> > > Can you re-generate the `index.js` with Node 20? We need to make sure it actually works with Node 20.
> > 
> > 
> > True, can do after work 👌 Thanks for the reply.
> 
> Hi @thomaseizinger - silly question, but how do I re-generate the index.js file?

Check the `package.json`, `yarn run build` should do the trick.

**Comment by NiharR027** [comment]
> > > > Can you re-generate the `index.js` with Node 20? We need to make sure it actually works with Node 20.
> > > 
> > > 
> > > True, can do after work 👌 Thanks for the reply.
> > 
> > 
> > Hi @thomaseizinger - silly question, but how do I re-generate the index.js file?
> 
> Check the `package.json`, `yarn run build` should do the trick.

Thanks @thomaseizinger will do, just got flat out busy with other work. I will mention you again once I do and push it here.

**Comment by NiharR27** [comment]
@thomaseizinger - I had to bump other packages in-order to run the command / build. Here is a PR that I created from my other account: https://github.com/thomaseizinger/create-release/pull/6/files.

We can close this PR once that one is good to go.

**Comment by NiharR027** [comment]
Closing in favor of: https://github.com/thomaseizinger/create-release/pull/6

**Pull request closed without merging**
