### PR TITLE
Upgrading deps and node to 20

### PR DESCRIPTION
**Pull request by NiharR27**
Including https://github.com/thomaseizinger/create-release/pull/4

### CODE REVIEW

**Comment by NiharR27** [comment]
Also gotta upgrade `ts-jest`

**Comment by NiharR27** [comment]
works now.

**Comment by NiharR027** [comment]
@thomaseizinger - this should be ready to review now :) Lemme know if you find something. Thnx!

**Review by thomaseizinger — COMMENTED** [review]
Could we do the reformatting in a different PR please? It is hard to review all the changes with that mixed in!

**Comment by thomaseizinger** [comment]
> Could we do the reformatting in a different PR please? It is hard to review all the changes with that mixed in!

I am surprised that there is even a formatting diff, I thought we had prettier set up in here.

**Comment by NiharR027** [comment]
> Could we do the reformatting in a different PR please? It is hard to review all the changes with that mixed in!

Sounds good can do 👍

**Comment by NiharR27** [comment]
Will open new one without reformatting.

**Comment by NiharR27** [comment]
@thomaseizinger  - created this PR: #7. Lemme know if that looks good :) or if there is anything to change. tq.

**Pull request closed without merging**
